### ISSUE TITLE
Never touched master branch, but have merge conflict?

### ISSUE THREAD

**Issue by binarykitchen** [petervanderdoes/gitflow-avh#123]
Hi there

This is weird. I work from home and from the office with the same repo. I always work with `git flow release` and do start/publish/finish whenever a sprint is done. The master branch is never touched. Code changes are supposed to get merged into master during a `git flow release finish`.

But I am having merge conflict sometimes when I do so. Weird. There shouldn't be any. Simply because I am the one and only developer and never make changes directly in the master branch.

What's the problem here? Why can't all changes in the release branch be merged into master without any "drama"?

**Comment by klday** [comment]
I'm having the same problem as above.  it's so frustrating.  I am getting merge conflicts where I should not have them.  I'm not the only one on my team experiencing this problem.  And, when I fix the merge conflicts, the same conflicts pop back up again when I rebase --continue.  Sometimes I'll get through rebase --continue, but on my next pull for my feature branch - same conflicts arise again.  I guess I should clarify that the conflicts are not exactly the same, but the same set of conflicts in the same spot kind of rotate in and out - if that makes sense.  At least, that is my perception of the merge conflicts and they point to the same 2 or 3 commits.  I am so tired of deleting my local repo and cloning it back.  This has been a huge time suck.  Any suggestions (I've tried the ones above and the problem continues to recur) would be greatly appreciated!

**Comment by rosskevin** [comment]
@binarykitchen I've got the same exact problem with a `package.json` version bump.  My `master` stays untouched and only CI performs `git flow release`.  What did you end up doing?

This was the merge conflict, which I have no comprehension why:

```
diff --git a/package.json b/package.json
index e6f850c..6f0a5c4 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "@alienfast/af",
-  "version": "2.1.18",
+  "version": "2.1.19",
   "description": "af - this is here only for unified versioning/releasing/discovery.",
   "scripts": {
     "release": "npm publish"
```

**Comment by binarykitchen** [comment]
dont remember, this ticket is from stone age

**Comment by redeemefy** [comment]
I'm having this issue now.

**Comment by rodrigorodriguescosta** [comment]
2020 and I have the same issue, nobody push to master, only from PR, some changes performed on source branch will show up message that has conflicts with master when create PR! how to resolve that?

**Comment by rodrigorodriguescosta** [comment]
I had the same issue and I fixed checking the option "Require pull request reviews before merging" on branch master protection rules, it was not checked but protection for master was added

![image](https://user-images.githubusercontent.com/3034127/76272487-4d332e80-625a-11ea-9e14-e82ca22905e4.png)

**Comment by Shahzad-tech** [comment]
Every time i was finishing a branch, it had a merge conflict issue with the branch to be merged in. For example Feature branch had always a merge issue with develop branch, release branch had always an issue with master branch. This issues has been solved by doing the following.
--> Always commit the changes locally to the branch which you are merging in. For example if you are finishing a feature branch, commit the changes locally to the develop branch first.

![image](https://user-images.githubusercontent.com/67801055/174965637-679a1012-b1a0-4ed4-9eb5-d933914e81ac.png)
 

Tools and Tech:  Angular 13, Visual Studio 2022, GitHub, GitFlow
