### ISSUE TITLE
Remove fast-forward merge in feature finish

### ISSUE THREAD

**Issue by petervanderdoes** [petervanderdoes/gitflow-avh#140]
Currently a fast-forward merge is done when there is only one commit in a feature branch.

The argument given at https://github.com/nvie/gitflow/issues/292#issuecomment-27331962 is a good argument to remove this behavior.

I could introduce a configuration variable that would make a 1 commit feature branch fast-forward. But default behavior will be no fast forward.

**Comment by krlmlr** [comment]
This is now orthogonal to the merge.ff option, which may or may not be what is desired. Anyway, thanks for implementing the option.
