### ISSUE TITLE
Make git flow work with remote branches

### ISSUE THREAD

**Issue by it-ony** [petervanderdoes/gitflow-avh#144]
Git flow works with local branches. Working in a team, one member e.g. starts a release branch and does `git flow release publish`.

It would be great if git flow had a reverse command to `publish`, to get all remote branches in `release/`, `hotfix/`, `feature/`, `support/` as tracked local branch.

**Comment by zheeeng** [comment]
@petervanderdoes We still need to pull down changes through raw git command, don't we have any improvement?

**Comment by petervanderdoes** [comment]
What are you thinking of? Do you want something like 'git flow feature pull <feature>' ?
