### ISSUE TITLE
Allow multiple hotfix branches to exist at the same time

### ISSUE THREAD

**Issue by elistevens** [petervanderdoes/gitflow-avh#167]
Our use case is:
- Release version 2.3.0
- Begin work on version 2.4.0, features merged to develop
- Two bugs are discovered in 2.3.0, both slated for 2.3.1

Right now, our only choices are to:
- Mix multiple bugs into one branch (bad from a testing and separation of concerns POV)
- Serialize development (bad from a "customers need this fixed ASAP" POV)
- Have developers not push their commits off their local dev box until they hotfix finish (which is also bad for testing)

I would also be happy with a 'bugfix' branch type that has the same merge semantics as hotfix, but allowed multiples, and didn't come with the implication of being a release to customers. Note that this conflicts with the request in #156. We currently use hotfix to fix issues that aren't severe enough to warrant a release by themselves, but that we know we'd like to roll into a release should a more serious issue arise. Generating release tags for those branches isn't really relevant.

**Comment by sciamannikoo** [comment]
Not working for me:
On Mac OS I should use `git config gitflow.multi-hotfix true` (without "--set", right?): if I run `git config --get gitflow.multi-hotfix` it does return, so it seem this is the right way to set this setting. If I use the "--set" argument I get an error anyway.

So, once this is set, I try to create a new hotfix, but it keeps saying I must close the existing hotfix.

**Comment by bill-bradley** [comment]
Did you install the latest develop branch, or the default release from brew install?  Be sure to use: brew install git-flow-avh --HEAD

**Comment by sciamannikoo** [comment]
Default release from brew.

Installed now from HEAD: I'll try as soon as I have other concurrent hotfixes (which is a rare case, I must admit).

**Comment by sciamannikoo** [comment]
Thanks so far.

**Comment by Ismaaa** [comment]
`git config --add gitflow.multi-hotfix true`

worked for me
