### ISSUE TITLE
Allow For Custom Commit Messages for Release

### ISSUE THREAD

**Issue by pietdaniel** [petervanderdoes/gitflow-avh#188]
### Custom Commit Messages

I use git flow to deploy to a production server. This creates three branch merge (release, develop, and master) which kicks off three continuous integration jobs with circle ci. It would be nice to specify a custom commit message on the release and develop branches in order to insert the "[ci skip]" flag which would prevent two unnecessary build jobs.

Something along the lines of 
`git flow release start #{version} --commit-message "[ci skip]"`

**Comment by petervanderdoes** [comment]
You can utilize the the hook: filter-flow-release-finish-tag-message
