### ISSUE TITLE
error when executing "git flow feature list"

### ISSUE THREAD

**Issue by gisphm** [petervanderdoes/gitflow-avh#197]
I am using the latest development version of git-flow. I found that when I executed `git flow feature list` in a git repository, it showed error message as below:

```
: not foundnt/tools/git/bin/git-flow: 37: /home/vagrant/tools/git/bin/git-flow-feature: 
: not foundnt/tools/git/bin/git-flow: 39: /home/vagrant/tools/git/bin/git-flow-feature: require_git_repo
: not foundnt/tools/git/bin/git-flow: 40: /home/vagrant/tools/git/bin/git-flow-feature: require_gitflow_initialized
: not foundnt/tools/git/bin/git-flow: 41: /home/vagrant/tools/git/bin/git-flow-feature: gitflow_load_settings
: not foundnt/tools/git/bin/git-flow: 43: /home/vagrant/tools/git/bin/git-flow-feature: }
: not foundnt/tools/git/bin/git-flow: 44: /home/vagrant/tools/git/bin/git-flow-feature: 
: not foundnt/tools/git/bin/git-flow: 63: /home/vagrant/tools/git/bin/git-flow-feature: flags_help
: not foundnt/tools/git/bin/git-flow: 64: /home/vagrant/tools/git/bin/git-flow-feature: }
: not foundnt/tools/git/bin/git-flow: 65: /home/vagrant/tools/git/bin/git-flow-feature: 
/home/vagrant/tools/git/bin/git-flow: 67: /home/vagrant/tools/git/bin/git-flow-feature: cmd_list: not found
: not foundnt/tools/git/bin/git-flow: 68: /home/vagrant/tools/git/bin/git-flow-feature: }
: not foundnt/tools/git/bin/git-flow: 69: /home/vagrant/tools/git/bin/git-flow-feature: 
: bad variable name/git/bin/git-flow: 79: local: len
```

I am using `git-2.3.4`(compiled by myself) on my ubuntu trusty virtual machine (it is created by vagrant box from [ubuntu cloud-images][1]). The shell I am using is `zsh 5.0.2`. And wherever I install git and git-flow (in /usr/local or in my home directory), the same error message will show up.

However, on my windows host machine, the command `git flow feature list` does not show any error message and `git flow feature start hello` executes sucessfully. I am using `msysgit v1.9.5.msysgit.1` on windows.

I am confused about the error message and wondering if I should downgrade git version on my virtual machine.
[1]: http://cloud-images.ubuntu.com/vagrant/

**Comment by petervanderdoes** [comment]
It has nothing to do with git-2.3.4, I run this myself and have no problems.

It almost seems like the file gt-flow-feature is corrupt. Can you copy past the first 39 line from that file as they are in your VM?

**Comment by gisphm** [comment]
I just copy the git-flow-feature file in this [gist][1].
[1]: https://gist.github.com/gisphm/fccc8655da6f5863a877

**Comment by petervanderdoes** [comment]
I don't see anything why you would get an error.
And it's only with `git flow feature list` you get the error?

**Comment by gisphm** [comment]
Not only `git flow feature list`, but also `git flow feature create` will run into error.

I just removed the local repo, re-clone a new one from github repo and reinstall git-flow. And I find that it works and shows nothing wrong. It seems so wierd.

**Comment by talios** [comment]
For reference - just updated `master@HEAD` here on OS/X and `git flow feature list` works fine for me using the latest git version.

**Comment by petervanderdoes** [comment]
@gisphm Can you run `DEBUG=yes git flow feature list 2> debug.txt` and show the contents of debug.txt?

**Comment by gisphm** [comment]
I am sorry for seeing the message too late. This is [`debug.txt`][1] after running `DEBUG=yes git flow feature list 2> debug.txt`.
[1]: https://gist.github.com/gisphm/eca60d058fe9b2eebff9

**Comment by petervanderdoes** [comment]
Based on the debug.txt I don;t see anything wrong.
You are running the command (https://gist.github.com/gisphm/eca60d058fe9b2eebff9#file-debug-txt-L313)
It works and says there are no feature branches. (https://gist.github.com/gisphm/eca60d058fe9b2eebff9#file-debug-txt-L846)
I have no clue why you get the error messages but it does not seem to be related to git-flow.

Did you install git-flow manually or through apt-get?
