### ISSUE TITLE
Rename the project to Gitflow2

### ISSUE THREAD

**Issue by gsklee** [petervanderdoes/gitflow-avh#204]
Hi @petervanderdoes, I discovered your fork from nvie/gitflow/issues/285. Checked around a bit and it appeared to me that [your contributions](https://github.com/petervanderdoes/gitflow/graphs/contributors) have already far outweighed that of the original author. Since the original project has gone dormant for nearly 3 years, and that Ubuntu is using your fork in their official repo, I think it'd help people find your active fork by renaming the name of this repo to `Gitflow2`. This kind of renaming has happened quite a lot of times before with things like "event-emitter / eventemitter2 / eventemitter3", "underscore / lodash" etc. when a fork has accumulated quite some differences against the upsteam.

**Comment by nmrony** [comment]
Can I propose `gitflow-avh`?

**Comment by srt32** [comment]
:+1:

**Comment by petervanderdoes** [comment]
Renamed to gitflow-avh

**Comment by gsklee** [comment]
@petervanderdoes Why not Gitflow 2? Gitflow-AVH sounds more like a spinoff than a successor, and actually I don't even know what AVH stands for...

**Comment by petervanderdoes** [comment]
Thanks @mgreensmith for updating the Homebrew formula.
