### ISSUE TITLE
Git for Windows paths are different in 2.x releases

### ISSUE THREAD

**Issue by nicg-corbas** [petervanderdoes/gitflow-avh#210]
The msysgit-install.cmd doesn't copy files to the correct location when git for windows 2.x is installed because the .../bin/ directory is not on the path. The files need to be moved to .../usr/bin/ after installation. Perhaps the script could check for the presence of /usr/bin and install there. Happy to submit a patch if you want but I'm not exactly a skilled windows user.

**Comment by viniciusmelquiades** [comment]
This seems a little more complex than that.
Git v2.x seems to use both the `/cmd` and the `/usr/bin`. If I move `git-flow-*` and `getopt.exe` files i either of those folder, it "works". Git flow commands are understood.

However, this is what happened when I tried to run git-flow
```
$ git flow feature                                                                                                                   
C:/Program Files/Git/cmd/gitflow-shFlags: line 149: _flags_fatal: command not found                                                  
C:/Program Files/Git/cmd/gitflow-shFlags: line 264: [: too many arguments                                                            
C:/Program Files/Git/cmd/gitflow-shFlags: line 264: [: too many arguments                                                            
C:/Program Files/Git/cmd/gitflow-shFlags: line 264: [: too many arguments                                                            
C:/Program Files/Git/cmd/gitflow-shFlags: line 1013: [: -ne: unary operator expected                                                 
flags:WARN                                                                                                                           
flags:FATAL unable to parse provided options with getopt.
```
This seems to happen for every command that tries to read the values from the git config (that's where I assume it stored my branches naming configuration).

Though I'm not an expert, I think I could fix the `msysgit-install.cmd` script, but I don't know what to do to make git-flow work.

**Comment by bill-bradley** [comment]
As a workaround, if you install the 32 bit version of git 2.5 instead of the 64 bit.  And then run:
`msysgit-install.cmd 'C:\Program Files (x86)\Git\usr'`, you should avoid the above errors.

**Comment by jakobehn** [comment]
Thanks for reporting this guys. I have made a change to how the GitFlow extension locates the installation path of msys-git. I have tried it on a couple of machines with v2.5 installed.
The experience after upgrading the extension will be that you are prompted to install GitFlow again, since the files need to be copied to the usr/bin location.
I would  be great to have some extra tests for this version, so I've published a draft release here with the vsix files. Would you mind trying these out before I publish them to the gallery? 

The release is here https://github.com/jakobehn/GitFlow.VS/releases/tag/v0.10.10

Thanks!

**Comment by petervanderdoes** [comment]
I'll see what I can do. Git for Windows moved to msys2, I need to install the portable version to see what I can do to fix this.

**Comment by gabrielpeixoto** [comment]
I am using git on version 1.9.5.

Any news?

**Comment by viniciusmelquiades** [comment]
I guess everyone forgot about this issue. I got it working for a while now.

I'm using git version `2.7.0.windows.1`, but it was working with earlier versions.

All I did was get the latest commits of this repository, navigated to the `contrib` folder and ran the command (I used powershell, but I think you can use anything) :
```powershell
.\msysgit-install.cmd "C:\Program Files\Git\usr"
```

The only difference in the command I ran and the command `.\msysgit-install.cmd`
 suggests me if I don't specify a path, is that I added a `\usr` at the end of the path.

And the *getopt.exe* file must be in the folder `C:\Program Files\Git\usr\bin` for 64 bits versions of GIT. I assume it must be in the folder `C:\Program Files (x86)\Git\usr\bin` for 32 bits versions

**Comment by HaveF** [comment]
@viniciusmelquiades but the error is still there...

```
/r/test$ git-flow init -h
/mingw64/bin/gitflow-shFlags: line 149: _flags_fatal: command not found
/mingw64/bin/gitflow-shFlags: line 264: [: too many arguments
/mingw64/bin/gitflow-shFlags: line 264: [: too many arguments
/mingw64/bin/gitflow-shFlags: line 264: [: too many arguments
/mingw64/bin/gitflow-shFlags: line 264: [: too many arguments
/mingw64/bin/gitflow-shFlags: line 264: [: too many arguments
/mingw64/bin/gitflow-shFlags: line 264: [: too many arguments
/mingw64/bin/gitflow-shFlags: line 264: [: too many arguments
/mingw64/bin/gitflow-shFlags: line 264: [: too many arguments
/mingw64/bin/gitflow-shFlags: line 1013: [: -ne: unary operator expected
flags:WARN
flags:FATAL unable to parse provided options with getopt.
```

**Comment by HaveF** [comment]
after delete the gitflow things under `C:/Program Files/Git/mingw64/bin/`, the error is still there:

```
/r/test$ git flow init -h
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 149: _flags_fatal: command not found
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 264: [: too many arguments
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 264: [: too many arguments
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 264: [: too many arguments
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 264: [: too many arguments
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 264: [: too many arguments
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 264: [: too many arguments
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 264: [: too many arguments
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 264: [: too many arguments
C:/Program Files/Git/usr/bin/gitflow-shFlags: line 1013: [: -ne: unary operator expected
flags:WARN
flags:FATAL unable to parse provided options with getopt.
```

**Comment by viniciusmelquiades** [comment]
what's your git installation path, git version, and command you're running?

**Comment by HaveF** [comment]
```
/r/test$ git --version
git version 2.6.3.windows.1
```
installed at `C:/Program Files/Git/`
reinstall with your command `.\msysgit-install.cmd "C:\Program Files\Git\usr"`

**Comment by viniciusmelquiades** [comment]
know you got me. If I did something else for mine to work, I don't remember.

What version of gitflow are you using? I did a git pull on this repository today just to test this. I'm using the `master` branch

**Comment by HaveF** [comment]
I'm using the newest `develop` branch. 
So, do all your git-flow commands work fine?
Feel headache about the shell script, or just leave it now....

**Comment by viniciusmelquiades** [comment]
@HaveF that's right. they just work.
I used to get the same errors you're getting right after I updated to git 2.0 (thanks to Chocolatey for changing to the 64 bit version without notifying me).

Thinking about it, it could be the getopt.exe I'm using. It's just a guess, but it is mentioned in your error message. I don't remember if I used the one provided on git-flow's wiki or if I downloaded some other version. I can send you the one I'm using if you want to try it out.

**Comment by HaveF** [comment]
@viniciusmelquiades thanks! depends on your comments, I tried getopt.exe (the version list in  https://github.com/nvie/gitflow/wiki/Windows ), it works now. thanks again!

**Comment by viniciusmelquiades** [comment]
@HaveF I'm glad it worked.

@petervanderdoes Perhaps you can find someone with git for Windows 32 bits and if they're not having trouble I think you can close the issue.

**Comment by linquize** [comment]
You need to support 3 types of path: git 1.9.5, git 2.x 32-bit,  git 2.x 64-bit
