### ISSUE TITLE
1.8.0 hacked?

### ISSUE THREAD

**Issue by kwuser** [petervanderdoes/gitflow-avh#218]
You sha256sum changed from 8239131b8dac160d7e929eab376fa14de44a55cbd5c5545e0ad4464d3a57adef

to

350665a9de7a9fe58ab82df5ef70c4e6c4f95bf844e30c23e2f3486396727511

also see as a reference: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/git-flow-avh.rb#L5

As i suggest you did not "re release 1.8.0" it could have been modified?

**Comment by petervanderdoes** [comment]
Interesting, I just did a comparison between the .tar.gz in the brew file and a archive created from my local repository and there is no difference.

I can think of one possibility for this to have happened.
- The archive was recreated after renaming the project and that changed the SHA.
