### ISSUE TITLE
Migration guide from vanilla gitflow

### ISSUE THREAD

**Issue by adamhadani** [petervanderdoes/gitflow-avh#219]
Hey,
very excited to see this fork so active! We've been using vanilla gitflow and while we love the workflow and the basic CLI functionality, it's very clear that staleness has become a big issue.
For the sake of users like us and many others who already use gitflow and would like to migrate to the gitflow-avh edition, I suggest adding a small 'migration guide' section to the Wiki. 
Some considerations:
1. OSX / Windows / Linux variations?
2. Should probably mention any known issues / incompatibilities between basic gitflow CLI usage and gitflow-avh 
3. what does AVH stand for? :)

Happy to help with this but would need basic input from people who've migrated successfully, only reference I found which was somewhat lacking is this:
https://groups.google.com/forum/#!topic/gitflow-users/ENIb6RCnIVg

**Comment by allisonfong** [comment]
:+1:

**Comment by srt32** [comment]
:+1:

**Comment by petervanderdoes** [comment]
1, Yes :) It should run on any flavor Linux, OSX and Windows.
2. Incompatibilities: If you move to gitflow AVH you can't use the original anymore. This is not entirely true but why would you go back :) Everything the original gitflow does, this version does plus more.
3. AVH: A Virtual Home. It's a website I started a long time ago, mostly to talk about linux kernels and writing WordPress plugins. With WordPress you need to prefix classes so you won't have conflicts with other developers. I used AVH, just brought that into this project.

**Comment by adamhadani** [comment]
thanks @petervanderdoes . any particular steps to install over old gitflow? e.g do i need to uninstall first / any known clashes if i just go ahead and install gitflow-avh while already installed gitflow via Homebrew?

**Comment by petervanderdoes** [comment]
I personally would uninstall the old git-flow before installing the AVH version. And that's just because I don't have a working Mac to see what happens when you just install the AVH version.
