### ISSUE TITLE
feature finish fails if no changes to merge

### ISSUE THREAD

**Issue by allancarter** [petervanderdoes/gitflow-avh#224]
If I finish a branch with no changes I get the following error:

Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
 (nothing to squash)Already up-to-date.
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean

There were merge conflicts. To resolve the merge conflict manually, use:
    git mergetool
    git commit

You can then complete the finish by running it again:
    git flow feature finish amc_test

Note that there are NOT any merge conflicts.

I know that this looks funny, but the usage model is that I want to run the commands on all submodules. So when I create a feature branch I want to branch the project and all of its submodules. When I finish it I want to finish the branches in all of the submodules. If the submodule had no commits then feature finish should just continue with no error.

**Comment by lgiordani** [comment]
@allancarter I can't reproduce it. Are you using the last gitflow version? May you please run the following bash code and tell if and where it fails?

``` sh
mkdir test_empty_feature
cd test_empty_feature

git init
git flow init -d

touch test.txt
git add test.txt
git ci -m "Just a test"

git flow feature start test1

git flow feature start test2
echo "test1" > test.txt
git add test.txt
git ci -m "Test fixed"
git flow feature finish

git flow feature finish test1

git br -avv
```

That "nothing to squash" is not what I expected. May you perhaps better describe your setup with submodules?
