### ISSUE TITLE
What does backmerge do in hotfix finish?

### ISSUE THREAD

**Issue by rcdailey** [petervanderdoes/gitflow-avh#227]
There is a `-b` option, but I'm not sure what a back-merge is. Can you explain this in more detail? Thanks.

**Comment by petervanderdoes** [comment]
If you use a tag on finish, the tag is done on the Master branch.
When you finish a hotfix, the hotfix branch is merged into Master. By default git-flow merges Master (including the tag commit) back into Develop. With the `-b` option the hotfix branch is merged into develop and therefor not the tag commit.
