### ISSUE TITLE
Ubuntu Installs Old Version

### ISSUE THREAD

**Issue by sataris** [petervanderdoes/gitflow-avh#234]
I'm not sure if this is the correct place for this. but running sudo apt-get install git-flow installs version 1.8.0 rather than 1.9.1

Of course I can install it manually but i'd rather not go down that path.

**Comment by petervanderdoes** [comment]
I do not maintain the PPA for Ubuntu. If I recall correctly I email the maintainer to notify of the updated version.

The official PPA can be found here: https://launchpad.net/ubuntu/+source/git-flow
