### ISSUE TITLE
Missing comparison document

### ISSUE THREAD

**Issue by schrepfler** [petervanderdoes/gitflow-avh#236]
In order to understand better of the pro's and differences of avh it would be good if there's a markdown document highlighting the differences and added features to avh.

**Comment by petervanderdoes** [comment]
I guess the best I can offer right now is to have a look at the [Changelog](https://github.com/petervanderdoes/gitflow-avh/blob/develop/Changes.mdown)
Basically read up from the release [0.4.2-avh1 ](https://github.com/petervanderdoes/gitflow-avh/blob/develop/Changes.mdown#042-avh1)

I think to much has changed over the past 4 years to create a page that will explain the differences.
