### ISSUE TITLE
Strange folder in repository, post merge 

### ISSUE THREAD

**Issue by par2** [petervanderdoes/gitflow-avh#237]
I was unsure whenever [this](https://stackoverflow.com/questions/33440103/strange-folder-showing-up-when-using-git-flow-on-windows) issue got posted/resolved yet.  I get a similar folder after using `mergetools vimdiff` to resolve conflicts.  I also am using 1.9.0-dev.59 (AVH Edition).

**Comment by petervanderdoes** [comment]
As mentioned, upgrading to git flow 1.9.1 will fix the problem

**Comment by par2** [comment]
Thank you.  Any suggestions on how to upgrade canonically?
