### ISSUE TITLE
Installation (OSX) without post installation setup gives warnings

### ISSUE THREAD

**Issue by buckett** [petervanderdoes/gitflow-avh#239]
I did a `brew install git-flow-avh` (installed 1.9.1) on OSX and afterwards running the `git flow ...` command would get warnings output.

    flags:ERROR short flag required for (showcommands) on this platform
    flags:ERROR short flag required for (local) on this platform
    flags:ERROR short flag required for (global) on this platform
    flags:ERROR short flag required for (system) on this platform
    flags:ERROR short flag required for (file) on this platform
    /usr/local/bin/gitflow-common: line 79: [: -eq: unary operator expected
    /usr/local/bin/gitflow-common: line 79: [: -eq: unary operator expected
    /usr/local/bin/gitflow-common: line 79: [: -eq: unary operator expected

Doing the setup that is [mentioned](https://github.com/petervanderdoes/gitflow-avh/wiki/Installing-on-Mac-OS-X#post-installation-setup) for 1.7.0 and before of:

    cat 'export FLAGS_GETOPT_CMD="$(brew --prefix gnu-getopt)/bin/getopt"' >> ~/.gitflow_export

then these warning disappear, is this the case of the documentation being wrong or has a bug been re-introduced?

**Comment by petervanderdoes** [comment]
Brew creates a file `bin/git-flow` which takes care of the gnu-getopt stuff. If for some reason your path is setup in a way that this is not used for the command git-flow but is using {lib-exec}/git-flow then you would get your error message.
