### ISSUE TITLE
[gitflow-avh 1.9.1] git flow release does not provide a consistent history across branches

### ISSUE THREAD

**Issue by jameskyle** [petervanderdoes/gitflow-avh#241]
After a git flow release is closed, the develop and master histories are not the same.

For example, here is the history for the master branch after a release:

    ceb57b2 (HEAD -> master, tag: 0.03, origin/master) Merge branch 'release/0.03' [James Kyle]
    9ecd10d Changed repository path to att-innovate [James Kyle]

And here is the develop branch

    a98d289 (HEAD -> develop, origin/develop) Merge tag '0.03' into develop [James Kyle]
    ceb57b2 (tag: 0.03, origin/master, master) Merge branch 'release/0.03' [James Kyle]
    9ecd10d Changed repository path to att-innovate [James Kyle]  

There's an 'extra' merge operation done on the devleop branch. The consequence is that clients like Github or bitbucket will see this as one branch being ahead of the other and generate a potential pull request.

Using the origin git-flow tools, for reference, would result in both master and develop having a HEAD of 9ecd10d.

**Comment by petervanderdoes** [comment]
After a release the master branch is tagged.
To account for `git describe` we merge the tag instead of master branch in develop.

Now the thing is, I just checked manually and if I merge master instead of tag, git describe still works. I'm not sure why there was a need to merge the tag instead of the master at the time this was implemented.
It could be it was never needed and it's just remains from the original comments in the code or git changed it's behavior when merging.

**Comment by jameskyle** [comment]
Thank you for the prompt response!

I see how the flow works with the merges, but the issue is that at the end of a release the different commit lines (develop/master/most recent tag) should all converge to a single HEAD. If they're not, then various git managers or sites like gitlab, bitbucket, or github will see the branches as having diverged and requiring a pull request to bring them back in sync.

**Comment by cdvv7788** [comment]
The extra commit makes sense to me. Once you start a release, the develop branch will diverge from the release process and requires that explicit merge to take that into account. After a release master will not have the same as develop, develop may be ahead of master. Master should be at the new tag tho.

**Comment by jameskyle** [comment]
Thank you for the thoughtful explanation. :+1:
