### ISSUE TITLE
What is AVH??

### ISSUE THREAD

**Issue by danielb2** [petervanderdoes/gitflow-avh#242]
I'm trying to select between gitflow and gitflow-avh and AVH  is mentioned multiple times, but never defined. Maybe a good thing to put in the FAQ?

**Comment by petervanderdoes** [comment]
AVH just stands for A Virtual Home. When I started developing, WordPress plugins, I needed a short prefix to distinguish my functions from others. I had the website avirtualhome.com for personal stuff, so I started using AVH.

**Comment by zx1986** [comment]
aha, it's all about personal :-)
