### ISSUE TITLE
Documentation never mentions what "AVH" stands for

### ISSUE THREAD

**Issue by AbeDillon** [petervanderdoes/gitflow-avh#243]
It's usually good form to spell out an acronym before using it. It's driving me crazy. I checked the project header, README, Wiki, FAQ, and google. I want to tell people about this cool project, but I can never remember the acronym.

"You should check out git-flow-... vhs? acv? ahv? something like that... It's a really great plug-in!"

A little blurb or link in the README is all I ask.

**Comment by mahlon-gumbs** [comment]
My guess is AVH is "A Virtual Home" since Peter van der Does' blog is hosted at http://blog.avirtualhome.com.  You can find links to some of the git-flow AVH archives there: http://blog.avirtualhome.com/category/software/git-software/git-flow/

**Comment by mahlon-gumbs** [comment]
Just noticed this: https://github.com/petervanderdoes/gitflow-avh/issues/242

**Comment by AbeDillon** [comment]
Thanks. It would be nice to link to AVirtualHome somewhere. I thought it was some jargon that I didn't know. It's weird how much it got to me.

**Comment by wadkar** [comment]
close?

**Comment by AbeDillon** [comment]
Sure, I guess. I would think the author (petervanderdoes) would want to promote his blog and alleviate some confusion by putting a simple link in the README or something, but I don't care enough to push the issue.
