### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by noopole** [petervanderdoes/gitflow-avh#244]
There's a Visual Studio Extension, that installs an extension for GitFlow. This extension will install GitFlow by itself. No installation instructions are needed.

Maybe you could add it to the Windows FAQ: 
http://blog.ehn.nu/2015/02/introducing-gitflow-for-visual-studio/

**Comment by petervanderdoes** [comment]
Cool, I'll add it. Thanks for the info
