### ISSUE TITLE
Two problems with Mac OS X installation steps

### ISSUE THREAD

**Issue by bdotzour-widen** [petervanderdoes/gitflow-avh#245]
The installation notes (both for wget and curl) reference an outdated URL to the installer script which is now returning a redirect.  wget is handling this, but curl is not.

1) The curl command needs to have the -L flag added to it to tell it to follow the redirect.

2) The one-liner using wget does not actually work, the arguments to the installer (e.g. install develop) are not properly getting passed into the command and you just get the usage message printed out.  I recommend just making this a two step process.

Also, I see other Issues related to broken Wiki steps .. would you consider making the wiki editable so that others could fix these types of issues when they find them?

**Comment by petervanderdoes** [comment]
I'll check it when I'm back from a trip next week.

**Comment by petervanderdoes** [comment]
I fixed the installer script instructions. I had to do with the rename of the repo.

**Comment by petervanderdoes** [comment]
Opened the wiki for now, I'll keep an eye out what happens and may close it again.
