### ISSUE TITLE
could not read Password error

### ISSUE THREAD

**Issue by noopole** [petervanderdoes/gitflow-avh#246]
When I want to terminate a feature, I select the command `Finish feature`, push the [OK] button, and get the following error in the console:

`fatal: could not read Password for 'http://[my_username]@[my_ip]:7990': Invalid argument`

Where can I set the password for my Git account?

**Comment by linquize** [comment]
`http://user:password@host:port/`

Alternatively, you may enable git credential helper

**Comment by noopole** [comment]
Thank you for your help.
