### ISSUE TITLE
`git flow init -d` does not work with `useconfigonly = true`

### ISSUE THREAD

**Issue by adam-moss** [petervanderdoes/gitflow-avh#259]
`git` 2.8 introduced a new configuration setting `useconfigonly` which, when set to `true`, will not allow operations to be performed unless a local `git config user.name = "x"` and `git config user.email = "y"` has been performed on a pre repo basis.

This is useful when the same device is used in multiple identity contexts (e.g. for work and hobby coding).

Currently if this option is configured `git flow init -d` results in the following:

```
Initialized empty Git repository in /Users/adam.moss/projects/test/.git/
Using default branch names.
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master] 
Branch name for "next release" development: [develop] 

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: no name was given and auto-detection is disabled
fatal: Not a valid object name: 'master'.
error: pathspec 'develop' did not match any file(s) known to git.
Fatal: Could not check out branch 'develop'.`
```

**Comment by petervanderdoes** [comment]
Fixed per commit 96ef4d056accf61a88004a5293566306c8b58289

Thank you for reporting
