### ISSUE TITLE
Develop branch push after feature finish

### ISSUE THREAD

**Issue by Kristian221** [petervanderdoes/gitflow-avh#261]
Is there a reason the develop branch doesn't automatically get pushed after you finish a feature branch? When finishing a release branch you can use '-p' to push automatically, it would be nice to have such a feature with feature branches.

**Comment by petervanderdoes** [comment]
Implemented with commit 53bb53669f0a0f57f1661c2b03fd5c56438a13fc

The flag is just `--push` as `-p` is already used for something else.
