### ISSUE TITLE
Add support for pull requests on branch finishing

### ISSUE THREAD

**Issue by adnux** [petervanderdoes/gitflow-avh#263]
Copyng the issue from old repository:
[Add support for pull requests on branch finishing](https://github.com/nvie/gitflow/issues/6364l):

Support for creating pull requests when finishing a branch would be a huge feature.

The ability to do the following:

git flow feature pull 0001

This would create a pull request for the current branch.

I would be happy to make a start on this, but my bash scripting is not too great so would need a little guidance.

**Comment by petervanderdoes** [comment]
Currently git-flow is POSIX compatible, no Bashism are used.
To use the Githb API we probably have to use a 3rd party library. I think it would possibly make it harder to keep it POSIX compatible if a external library is used.

**Comment by petervanderdoes** [comment]
Right now I'm closing this, besides GitHub, there is BitBucket, GitLab etc. With shell it's close to impossible to support every single one.

**Comment by bmcdonnell-fb** [comment]
For anyone's future reference, the link in the OP is broken (extra character appended on the URL). Here is the correct link:
https://github.com/nvie/gitflow/issues/6364
