### ISSUE TITLE
`git flow feature finish` fails when remote branch has already been deleted

### ISSUE THREAD

**Issue by vdh** [petervanderdoes/gitflow-avh#264]
```
fatal: Couldn't find remote ref feature/foo
Fatal: Could not fetch feature/foo from origin.
```

Since GitHub PRs offer to delete a branch after it's been merged, the remote is almost always already gone by the time I want to clean up my local branches.

**Comment by petervanderdoes** [comment]
git flow does not play well with the PR system of GitHub.

Personally I never use the PR fully.

**Comment by vdh** [comment]
But this issue is not present in [nvie/gitflow](https://github.com/nvie/gitflow), which detects the missing remote branch and skips it.

**Comment by petervanderdoes** [comment]
What version of git-flow are you running?

**Comment by vdh** [comment]
0.4.1

**Comment by petervanderdoes** [comment]
Time to upgrade. The current version is 1.9.1 released on Oct 20,2015.
Version 0.4.1 was released on Feb 14, 2011.

**Comment by vdh** [comment]
I was talking about [nvie/gitflow](https://github.com/nvie/gitflow) version 0.4.1, the original that doesn't exhibit this issue.

**Comment by shalomb** [comment]
For future readers, as observed in #343 .. it may help to set
```
git config gitflow.feature.finish.keepremote true
```
This prevents `gitflow` from attempting to delete the remote branch on a `git flow feature finish ...`
