### ISSUE TITLE
Release finish: Single squash commit?

### ISSUE THREAD

**Issue by keybounce** [petervanderdoes/gitflow-avh#268]
So the observed behavior, and looking over the script, the actual intended behavior for git flow release finish, with squash, seems to be:

1. Make a squash commit of the branch to master (good).
2. Make a squash commit of master to develop (???)

I'd like to know why it is not doing a normal commit of master to develop, specifically to keep git's tracking of changes. 

What I thought would happen was that a messy branch would be cleaned up for readability, and committed as a unit to master (which it did) and from there to develop (based on the picture associated with gitflow).

**Comment by petervanderdoes** [comment]
I believe you are on to something here.

There is an option for not back merging the master/tag into develop, but just merge the release branch in the develop branch. In that case teh squash should still be used but if you backmerge I believe you are right and there is not need to squash the commit.

**Comment by petervanderdoes** [comment]
Fixed per commit 1609299

**Comment by keybounce** [comment]
Thank you (now to wait for a release)

On 2016-07-23, at 5:22 PM, Peter van der Does <notifications@github.com> wrote:

> Fixed per commit 1609299
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Entertaining minecraft videos
http://YouTube.com/keybounce
