### ISSUE TITLE
[Question] Does support branch allow release start/finish?

### ISSUE THREAD

**Issue by dkirrane** [petervanderdoes/gitflow-avh#271]
Can I run release start and finish on a support branch?

Will this create a tag on the support branch?

**Comment by petervanderdoes** [comment]
Yup,

With the latest develop version.

**Comment by dkirrane** [comment]
Great, when do you plan to release what's on development?

**Comment by petervanderdoes** [comment]
Did yesterday :) Version 1.10.0
