### ISSUE TITLE
git flow release does not pull origin/develop automatically

### ISSUE THREAD

**Issue by pke** [petervanderdoes/gitflow-avh#278]
Is that a bug or intentionally?

**Comment by petervanderdoes** [comment]
Intentional. You can use the flag `--fetch` to fetch. If you always want to fetch you set it in the git config file, see https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration

**Comment by pke** [comment]
I guess thats kind of a protection so that if I decide to create a release branch from develop I first manually update my develop branch (to a commit I want to branch off from). Because in the meantime somebody else from the team could have merged a feature/bugfix/hotfix into develop and I would branch off a different HEAD I intended to?
