### ISSUE TITLE
Using ssh to clone repos disable use of 'new-pull-request' command.

### ISSUE THREAD

**Issue by avaz** [petervanderdoes/gitflow-avh#280]
Hi,

I have different accounts in Github and Bitbucket and to access them I use ssh with multiple keys. So in my ssh config file I have something like:
```
Host bitbucket-as-account2
  HostName bitbucket.org
  User git
  IdentityFile /Users/anderson/.ssh/id_rsa.pub
  IdentitiesOnly yes

Host github-as-account1
  HostName github.com
  User git
  IdentityFile /Users/anderson/.ssh/dev_andersonvaz_rsa.pub
  IdentitiesOnly yes
```

And to clone repos of these servers I do something like:
```
git clone git@github-as-account1:user/repo.git
```
Everything works but the 'new-pull-request' feature:
```
Error
  Unsupported hosting service.
  This command requires hosting on GitHub or Bitbucket.
```
It can't identify which server is being used.
I don't think that it's a bug so I will let this here as suggestion.
If was possible to specify which hosting service the pull request should be created or automatically resolves from `config` file which service the repo is using would be nice.

**Comment by petervanderdoes** [comment]
Which command are you running that gives the error message?

**Comment by avaz** [comment]
```git new-pull-request```

**Comment by avaz** [comment]
BTW, the command ```git repo``` fails with the same error message in this scenario.

**Comment by petervanderdoes** [comment]
I think you are at the wrong project. This project does not have either of the commands you say fail.

**Comment by avaz** [comment]
Hey @petervanderdoes, that's true, I confused the projects. Sorry!

**Comment by petervanderdoes** [comment]
Not a problem :) Out of curiosity which project where you talking about? I'm always looking for goof git projects.

**Comment by avaz** [comment]
The project that I supposed to open the issue is this one:
[Git Town](https://github.com/Originate/git-town)
