### ISSUE TITLE
git flow feature checkout fails for nameprefix

### ISSUE THREAD

**Issue by superole** [petervanderdoes/gitflow-avh#284]
My versions:

    $ git version
    git version 2.9.3.windows.1
    $ git flow version
    1.9.1 (AVH Edition)

My feature branches:

    $ git flow feature
      XX-123-fix-for-a-numbered-issue
      XX-199-another-detailed-task

Documentation states that git flow feature checkout can take `name|nameprefix` as arguments.

Executed command:

    $ git flow feature checkout XX-199

Expected result: branch _feature/XX-199-another-detailed-task_ is checked out

Actual result:

    error: pathspec 'feature/XX-199' did not match any file(s) known to git.
    Fatal: Could not check out branch 'feature/XX-199'

This is working in the nvie-git-flow, and I find it quite handy.

**Comment by petervanderdoes** [comment]
Fixed per commit  9c68da2
