### ISSUE TITLE
problem with vi on hotfix finish

### ISSUE THREAD

**Issue by renewooller** [petervanderdoes/gitflow-avh#293]
Hi, 
I'm getting the following error:

`git-flow hotfix finish list-description-update`
`error: There was a problem with the editor 'vi'.`
`Please supply the message using either -m or -F option.`
`Fatal: Tagging failed. Please run finish again to retry.`

I don't have time to fix it at the moment, just thought I'd lodge it though to keep track of it.
If there's a known easy solution, let me know. 
Cheers,
Rene

**Comment by petervanderdoes** [comment]
You seem to have setup git to use vi for commit editing and the system can't find vi.

**Comment by renewooller** [comment]
I would have thought so also. The strange thing is that when I do other operations that require an editor using git, it will fire up vi without any error.

**Comment by petervanderdoes** [comment]
The only thing I can think of is that you have some settings `~/.gitlfow_export` that mess things up

**Comment by renewooller** [comment]
have solved this thanks to:
http://tooky.co.uk/there-was-a-problem-with-the-editor-vi-git-on-mac-os-x/
I actually did have a problem commit messages in VI. The problem is still a little mysterious, but adding:

git config --global core.editor /usr/bin/vim

has fixed the issue. Git flow is working fine now.

**Comment by petervanderdoes** [comment]
Yup mysterious indeed. But glad it's solved right now.
