### ISSUE TITLE
Mac missing symlinks after install

### ISSUE THREAD

**Issue by davdenic** [petervanderdoes/gitflow-avh#296]
i just install it with 
brew install git-flow-avh

but 2 links are missing:

gnu-getopt -> ../Cellar/gnu-getopt/1.1.6
gettext  -> ../Cellar/gettext/0.19.6

while git-flow-avh -> ../Cellar/git-flow-avh/1.9.1 was ok

git version 2.7.4 (Apple Git-66)

after manually add those links it works properly
bye :)

**Comment by petervanderdoes** [comment]
This is a homebrew issue. The recipe on homebrew should take care of the symlinks
