### ISSUE TITLE
Config to default no-tag flag to true? 

### ISSUE THREAD

**Issue by mkay581** [petervanderdoes/gitflow-avh#299]
Hello, I'm using [hubflow](https://datasift.github.io/gitflow/) and not sure if this is the repository to open an issue but research has pointed me here.

There is an option to pass `git hf hotfix finish [VERSION]` a  `-n` flag to prevent a git tag from being created when the hotfix is completed. There are a number of projects where I have to remember to pass this flag due to them having their own internal tagging process. Having to remember makes it easy to forget :)

This `no-tag` flag is false by default. Is there a way to set this `no-tag` flag to `true` in the configuration or similar so that I never have to worry about passing it every time I use the finish command?

**Comment by ruiming** [comment]
see https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration

**Comment by petervanderdoes** [comment]
Hubflow is a different implementation.
