### ISSUE TITLE
Support GitHub API

### ISSUE THREAD

**Issue by mknippen** [petervanderdoes/gitflow-avh#304]
One of the missing features for gitflow is the ability to open a pull request. When our team (and many others that I've heard of) finish a feature, they don't merge directly into develop, they open a pull request to allow a code review. It would be great if this was a customizable setting on gitflow, allowing us to finish a feature, and getting back the link for the pull request automatically.

The GitHub API supports this, and I think it would be the biggest differentiation from gitflow & gitflow-avh. Of course, it would be set at config time, and those who don't use it wouldn't have to.

**Comment by EduardoRT** [comment]
Yeah, I don't get why this isn't more requested in both of these projects, if you're not doing PRs then you're just using aliases to merge and create branches, I don't see much benefit to any of these projects without the ability to submit a PR and work with my teammates.

This doesn't mean I'm not using the aliases the project provides though.

**Comment by petervanderdoes** [comment]
In the current setup it's pretty hard to accomplish. There is a BASH lib to interact with the GitHub API, but the current strength of git-flow is that it run POSIX shell, meaning it can run on almost any machine with a shell.

Maybe if I get my skills up in Golang, I could rewrite this whole thing in Golang. :)  But for now support for the Github API is not in the future.

**Comment by EduardoRT** [comment]
@petervanderdoes Thank you so much for your answer, I understand the feeling of keeping something true to its original goals; rewriting this in Go would be awesome and a really nice goal to get this going.

Again, I thank you for your project, I still use it every day.

**Comment by petervanderdoes** [comment]
Closing this for now.
