### ISSUE TITLE
Surprising (unwanted) behavior with AVH `git flow release finish`

### ISSUE THREAD

**Issue by slawo** [petervanderdoes/gitflow-avh#305]
Why does `git flow release finish <release>` merge master back to develop?

This is contrary to the original git flow implementation and it seems to be enabled by default.

It there a way to avoid bringing master back to develop when we `finish` a release or anything else?

**Comment by maldag** [comment]
I guess the idea is to make sure develop is up to date with master.

**Comment by slawo** [comment]
@maldag Develop is supposed to receive changes from release and hot fix only.
Any other commits in master that are not made in develop are supposed to be specific to the master branch. It then becomes the responsibility of the team to manage these changes.

In the original gitflow master is moved into develop only when develop is created. Auto magically merging master into develop was not the intended behavior in the original gitflow.

It should never happen unless the team decides otherwise.

**Comment by slawo** [comment]
@maldag, in the original gitflow master is moved into develop only when develop is created. Auto magically merging master into develop was not the intended behavior in the original gitflow.

Master is supposed to receive changes from `release` and from `hotfix` only.
Develop is supposed to receive changes from `feature`, `release` and `hotfix`. Some people or teams will add more commits to develop, but this is up to them. But outside of the creation of develop there is no case where commits to master are supposed to be moved to develop.
Commits in master that are not made in develop are supposed to be specific to the master branch. It then becomes the responsibility of the team to manage these changes. So it should never happen automatically.

**Comment by slawo** [comment]
A very common and simple example is this:

You create a project.
In the develop branch you add a readme with some [shields](https://shields.io).
Once you release the project in the master branch you will changes the shields to reference the master branch.
If you never change these again you will have real information about the develop branch in the develop branch, and you will have the information about the current status of the published master branch in the master branch.
If you merge changes from master back to develop you loose the current status of the develop branch in the readme when you look at this branch. And while this is the branch your team wants to see, merging master back to develop will mess things up.

Same thing with more specific info, configuration or test files that are specific for the master branch. The original gitflow did not make assumptions about people being unable to understand what they do with their master branch.

**Comment by vukanac** [comment]
Maybe this created confusion:

> Finally, the changes made on the release branch need to be merged back into `develop`, so that future releases also contain these bug fixes.
* source: [nvie](http://nvie.com/posts/a-successful-git-branching-model/)

If we are looking the same picture, I see an arrow from master to develop.
> [hotfix example](http://nvie.com/img/hotfix-branches@2x.png)

Maybe your point of view contains valid requests, for badges etc.... but maybe additional options in git flow.

    git flow release finish -b

Help:

    -b, --[no]nobackmerge          Don't back-merge master, or tag if applicable, in develop

**Comment by petervanderdoes** [comment]
O long time ago this was a discussion at nvie. It has to do with `git describe` See https://github.com/nvie/gitflow/issues/49
