### ISSUE TITLE
Install instruction not working

### ISSUE THREAD

**Issue by TwanoO67** [petervanderdoes/gitflow-avh#308]
Hello guys,

In the installation part of the Readme, the mac version with curl, is not up to date.

in the command:
`curl https://raw.github.com/petervanderdoes/gitflow-avh/develop/contrib/gitflow-installer.sh > gitflow-installer.sh`

the link should be: 
`https://raw.githubusercontent.com/petervanderdoes/gitflow-avh/develop/contrib/gitflow-installer.sh`

because the link with raw.github.com is a redirection to that, and curl won't follow this redirection, so the script will be empty.

( I suppose that other links in the doc should be updated to )

**Comment by petervanderdoes** [comment]
Thank you for reporting.
Fixed.
