### ISSUE TITLE
Features with a single commit only are merged using fast-forward

### ISSUE THREAD

**Issue by Dominik1123** [petervanderdoes/gitflow-avh#312]
Finishing a feature which contains only a single commit is merged using fast-forward. Not sure if this is intended, i.m.o. fast-forward should never be used for features for the sake of clearness (+ this creates inconsistency with respect to 2+ commit features).

**Comment by petervanderdoes** [comment]
This is intentionally. It was the way it was setup in the original git-flow and was a subject to a big debate.

You can use the flag ``--no-ff`` to not use fast-forward. This flag can be set as a default as well. See more info for that on the [wiki page](https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration#git-flow-feature) (This is linked to the feature command but other commands have the same functionality).
