### ISSUE TITLE
develop branch policy only allows merges via pull request

### ISSUE THREAD

**Issue by mayerc-MSFT** [petervanderdoes/gitflow-avh#313]
Our **develop** branch's policy is configured such that merges are only allowed via pull request (Visual Studio Online).  `release finish` merges changes from the release branch onto **master** and **develop**.  We want the merge into **master**, but not into **develop** (due to policy).

What are your thoughts on adding a flag to `release finish` to skip the merge into develop (only merge into master)? Something along the lines of `git flow release finish -nodevelopmerge ...`

I've coded the changes in a private fork and they're pretty simple.  I'll be happy to submit pull request if you think this makes sense.

**Comment by bradym** [comment]
This feature already exists...

```
$ git-flow version
1.10.2 (AVH Edition)

$ git-flow release finish --help
usage: git flow release finish [-h] [-F] [-s] [-u] [-m | -f] [-p] [-k] [-n] [-b] [-S] <version>

    Finish a release branch

    <snip>
   
    -b, --[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
```

**Comment by mayerc-MSFT** [comment]
Thanks @bradym .  Doesn't -b suppress the merge from release into master (in addition to develop)?

The change I'm proposing is to suppress the merge into develop **but keep the merge into master.**

**Comment by bradym** [comment]
Nope, it merges to master but does not try to backmerge to develop. I've been using this command for awhile and it's working great:

```
git flow release finish --showcommands --nobackmerge --nopushdevelop --pushproduction --pushtag --tagname TAGNAME --message MESSAGE RELEASENAME
```

Even though some of those options are the default, I try to always be explicit about what's happening so I don't have to guess later when I'm editing a script.

**Comment by mayerc-MSFT** [comment]
@bradym Sweet. I could swear I got different results when I tried -nobackmerge last time.  I'll give this another try when I get to office. Thanks a lot for sharing the command you use.

**Comment by petervanderdoes** [comment]
If you want the no back merge to be a default option you can do:

`git config --bool gitflow.release.finish.nobackmerge true`

This way you no longer have to remember to enter the option `--nobackmerge` on a finish.

git-flow adheres to reading the config file like git itself, so you can use the options `--local`, `--system', or '--global` to set the options depending on your preference.

For more options like this see: https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration#reference-configuration

**Comment by dmurat** [comment]
As I understood after looking into the source of git-flow-release script, nobackmerge flag does not prevent merge into develop. It only selects weather master (default) or release (nobackmerge) branch will be merged into develop.

I will really like the nodevelopmerge option which will prevent any kind of merge into develop during finishing a release. 

In my case, during preparing a release I only change version numbers from snapshots into fixed numbers. Therefore, merging back either master or release, puts that fixed versions into develop which is undesired and I need to change them back to snapshots before continuing.

**Comment by petervanderdoes** [comment]
That's where filters come in handy, see for an example, that I actually use, what you can do with hooks and filters:
https://github.com/petervanderdoes/general-hooks

After a release the script `post-flow-release-finish` runs which updates the version info in the develop branch

**Comment by dmurat** [comment]
I see. However, this still looks like more involved than using simple command line switch. It looks like other folks will also prefer such solution. At least they are all thinking that nobackmerge prevents any merge into develop rather then merging release instead of master. It looks like they need, including me, a simple solution for preventing merge into develop. Could you, please, consider supporting something like this?

**Comment by mayerc-MSFT** [comment]
@petervanderdoes unfortunately I don't think (or at least can't see how) a filter/hook can meet our team's needs.  It feels like filters/hooks are an awesome solution for executing _additional_ logic/steps, but _not for skipping/disabling_ behavior baked into `git-flow-release`.  Is that so?

I'd love a simple switch to disable the merge back into dev and sounds like a cmdline switch would work great for @dmurat's needs to.

I've implemented `nodevelopmerge` in a fork and our team has been using it for a few weeks with good results.

I'll be happy to send a pull request if you're open to the idea.

**Comment by petervanderdoes** [comment]
@mayerc-MSFT Feel free to open an PR.

Just so everybody knows that doing this, meaning opt to not merge your release back into your develop branch, will create a diversion between your master branch and develop branch as there will be commits on your master that will never be in your develop branch.

**Comment by czeslav87** [comment]
@mayerc-MSFT I'd love to see that PR. We're having the same flow.
@petervanderdoes Good point. Good solution for such workflow would auto-merge (master->develop) hook on origin repo.

**Comment by mayerc-MSFT** [comment]
Created PR here: https://github.com/petervanderdoes/gitflow-avh/pull/317

@petervanderdoes @czeslav87 @dmurat

**Comment by petervanderdoes** [comment]
Feature added.

**Comment by chenjianjx** [comment]
Need the same thing for  "hotfix finish" as well.
