### ISSUE TITLE
How to deinit or reinit

### ISSUE THREAD

**Issue by johngeorgewright** [petervanderdoes/gitflow-avh#321]
Within one of my repos git flow seems to be bit broken:

```
$ git flow config
Fatal: Not a gitflow-enabled repo yet. Please run 'git flow init' first.
$ git flow init
# nothing happens
$ git flow config
Fatal: Not a gitflow-enabled repo yet. Please run 'git flow init' first.
```

Is there something I can do to remove/reinit git flow from a project?

**Comment by vzamanillo** [comment]
Edit your repo config file and add/edit the following values to:

```
vim yourrepo/.git/config

[gitflow "branch"]
        master = master
        develop = development
[gitflow "prefix"]
        feature = feature/
        release = release/
        hotfix = hotfix/
        bugfix = bugfix/
        versiontag = ""
```
save and start using gitflow :)

**Comment by petervanderdoes** [comment]
What version are you running?
`git flow version`

**Comment by johngeorgewright** [comment]
1.11.0 (AVH Edition).

Installed with brew.

**Comment by johngeorgewright** [comment]
OK, still unsure what the problem was, however, what seemed to fix it was *removing* all references to `gitflow` in `[repo]/.git/config` and then running `git flow init` again.
