### ISSUE TITLE
How does one format the config file for `git flow init`?

### ISSUE THREAD

**Issue by sjlongland** [petervanderdoes/gitflow-avh#350]
Hi,

Silly question, I had occasion to call `git flow init` programmatically in a script that sets up a development environment for a number of git repositories.  Apparently `git flow init` can take a config file for input, but nowhere could I see how this was documented.

I ended up doing this instead:
```
		# Check out repository
		( cd "${parentdir}" && \
			git clone ${repo} ${baseworkdir} && \
			cd ${baseworkdir} && \
			git flow init <<EOF
master
develop
feature/
bugfix/
release/
hotfix/
support/
v
${PWD}/.git/hooks
EOF
		)
```

This will break if the questions change for whatever reason, and thus is fragile.  How do I do the equivalent giving a configuration file?

**Comment by aram535** [comment]
`git flow init -d`

it takes all of the default values and asks no questions.

If you want to do it manually so you can change the values, here are the commands that init runs with those default answers.

`
git config gitflow.branch.master master
git config gitflow.branch.develop develop
git symbolic-ref HEAD refs/heads/master
git commit --allow-empty --quiet -m Initial commit
git branch --no-track develop master
git checkout -q develop
git config gitflow.prefix.feature feature/
git config gitflow.prefix.bugfix bugfix/
git config gitflow.prefix.release release/
git config gitflow.prefix.hotfix hotfix/
git config gitflow.prefix.support support/
git config gitflow.prefix.versiontag
git config gitflow.path.hooks E:/src/tmp/.git/hooks
`

**Comment by sjlongland** [comment]
Ahh okay, so conceivably I could do
```
git flow init -d
git config gitflow.prefix.versiontag v
```
to achieve the same thing as a work-around.  No worries. :-)
