### ISSUE TITLE
Git flow disable option to tag on release or hotfix

### ISSUE THREAD

**Issue by jper92** [petervanderdoes/gitflow-avh#362]
I sometimes end up using tools like maven release or npm, they both offer me the option to version my current code, which in addition create a tag for me. Given this behavior, whenever I bump my version inside a release or hotfix, I end up with 2 tags per version, the one npm/mvn creates and the one gitflow creates. 

Is there a way, like in a config file, where I state that I don't want git flow to create a new tag? I know there's a param you can pass when finishing the release or hotfix but I'd like to finish them and that git flow was aware of how is the project preference for the repo

**Comment by jkankiewicz** [comment]
> Is there a way, like in a config file, where I state that I don't want git flow to create a new tag?
 
Yes e.g.
```
git config --global gitflow.release.finish.notag true
git config --global gitflow.hotfix.finish.notag true
```

**Comment by jper92** [comment]
Is it documented somewhere by the way? Maybe I missed it

**Comment by jper92** [comment]
Nvm I found it in the wiki, sorry for the spam
https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration#git-flow-hotfix
