### ISSUE TITLE
Ubuntu 18.04 Bionic Beaver not supported

### ISSUE THREAD

**Issue by manuelmager** [petervanderdoes/gitflow-avh#366]
Is there any plan on supporting Ubuntu 18.04? Can you give a rough estimate on when it will be available? After adopting gitflow for the whole development team years ago, it came as quite a surprise to see it unavailable.

**Comment by NobbZ** [comment]
Do you experience any issues with the manual approach or is this just complaining about the messing prebuilt packages on the PPA?

**Comment by manuelmager** [comment]
Sorry, the manual approach works fine. Closing this.
