### ISSUE TITLE
Release finish does not create a signed tag

### ISSUE THREAD

**Issue by isaacramthal** [petervanderdoes/gitflow-avh#369]
Hi,

Is there any way that I can force 'git flow' to use signed tags when I finish my release branch?  This is true for Hotfix as well.

Currently, the commits are signed but the tags aren't.

**Comment by pxgamer** [comment]
You can use `git flow release finish -s` or `git flow hotfix finish -s`. But I don't think you can force it to sign tags by default.

**Comment by isaacramthal** [comment]
`-s` works...!

Thanks a lot.
