### ISSUE TITLE
Missing release for v1.12.2?

### ISSUE THREAD

**Issue by dscho** [petervanderdoes/gitflow-avh#406]
The other releases seemed to have full release notes, not just a tag. See https://github.com/petervanderdoes/gitflow-avh/releases: v1.12.2 only has a tag, v1.12.1 has a full description of the ChangeLog.

**Comment by hylke94** [comment]
This causes no update on Manjaro install. Which means no fix for #405 in latest public release! Releases on GitHub also says that 1.12.1 is the latest released version... Please fix.

**Comment by dscho** [comment]
@hylke94 in Git for Windows, I worked around it by hard-coding "if it claims the latest release is v1.12.1, it really is v1.12.2": https://github.com/git-for-windows/build-extra/commit/23dfa00f7a534edc02cb9bdad8f06a59251a8ab1. Maybe Manjaro can follow this inspiration to work around this here issue?

**Comment by hylke94** [comment]
The Manjaro aur package manager somehow sees the 1.12.2 version now. So I updated it and the init error  error (#405) is fixed ;).

**Comment by dscho** [comment]
Anyway, @petervanderdoes seems not to read issues, so I guess this issue was unintentionally "addressed" by releasing v1.12.3 (*with* release notes, so all is good).

**Comment by dscho** [comment]
Slightly unrelated: @petervanderdoes did you plan on accepting [sponsors](https://github.com/sponsors)? I imagine that quite a few Git for Windows users who were eager to see git-flow integrated would also be eager to see you supported financially in supporting the tool they so love.

**Comment by petervanderdoes** [comment]
@dscho I didn't even know sponsors existed. I have signed up on the waiting list. Thanks for the info
