### ISSUE TITLE
Can not delete branch

### ISSUE THREAD

**Issue by hanriiver** [petervanderdoes/gitflow-avh#473]
`git flow feature finish findByUserId
Fatal: The base 'feature/register' doesn't exists locally or is not a branch. Can't finish the feature branch 'feature/findByUserId'.`

I'm going to finish the function of the brunch that I finished requesting. However, these errors do not resolve them.

**Comment by Shea690901** [comment]
What happened to the `feature/register`branch?

**Comment by hanriiver** [comment]
We've solved this problem
